Repository canonical/hockeypuck-k8s-operator, pull requests merged in 2025-04, with the labels that each got.

#24 Changes to block_key action
  .github/workflows/publish_charm.yaml
  .gitignore
  .woke.yaml
  hockeypuck_rock/block_keys.py
  hockeypuck_rock/delete_keys.py
  hockeypuck_rock/rebuild_prefix_tree.py
  hockeypuck_rock/rockcraft.yaml
  lib/charms/operator_libs_linux/v0/apt.py
  requirements.txt
  src/actions.py
  src/admin_gpg.py
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
Labels: Libraries: OK

#55 Remove changelog temporary to let discourse-gatekeeper bootstrap the docs directory
  CHANGELOG.md
  docs/changelog.md
Labels: Libraries: OK

#94 Add changelog.md
  docs/changelog.md
Labels: Libraries: OK

#92 Charm Compliance
  .github/workflows/integration_test.yaml
  .github/workflows/load_test.yaml
  .github/workflows/promote_charm.yaml
  .licenserc.yaml
  docs/changelog.md
  icon.svg
  renovate.json
  src/admin_gpg.py
  src/charm.py
Labels: Libraries: OK, trivial

#58 Documentation
  CONTRIBUTING.md
  README.md
  charmcraft.yaml
  docs-template/explanation/charm-architecture.md
  docs-template/how-to/contribute.md
  docs-template/index.md
  docs-template/reference/actions.md
  docs-template/reference/configurations.md
  docs-template/reference/integrations.md
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/how-to/backup-and-restore-hockeypuck.md
  docs/how-to/contribute.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/manage-admin-keys.md
  docs/how-to/manage-gpg-keys.md
  docs/how-to/reconcile-between-two-keyservers.md
  docs/how-to/upgrade.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/integrations.md
  docs/reference/metrics.md
  docs/reference/ports.md
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: OK

#102 Change publish charm track from latest to 2.2
  .github/workflows/promote_charm.yaml
  .github/workflows/publish_charm.yaml
  docs/changelog.md
Labels: Libraries: Out of sync, trivial

#103 Cos integration fixes
  docs/changelog.md
  src/cos/grafana_dashboards/hockeypuck.json
  src/cos/prometheus_alert_rules/error_rate.rule
Labels: bug, Libraries: OK, trivial
